# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10uYJkZ_IZ-ll8LrFbwTVn1aGXm71PkNr
"""

import requests
import json

def get_posts():
    try:
        # Отправляем GET-запрос к API
        response = requests.get('https://jsonplaceholder.typicode.com/posts')

        # Проверяем успешность запроса
        response.raise_for_status()

        # Преобразуем JSON-ответ в Python-объект
        posts = response.json()

        # Выводим первые 5 постов
        print("=== Первые 5 постов ===")
        for i, post in enumerate(posts[:5], 1):
            print(f"\nПост #{i}")
            print(f"Заголовок: {post.get('title', 'Нет заголовка')}")
            print(f"Текст: {post.get('body', 'Нет текста')}")
            print("-" * 50)

        return posts[:5]

    except requests.exceptions.RequestException as e:
        print(f"Ошибка при запросе: {e}")
        return None
    except json.JSONDecodeError as e:
        print(f"Ошибка при обработке JSON: {e}")
        return None

# Альтернативная версия с более аккуратным форматированием
def get_posts_formatted():
    try:
        response = requests.get('https://jsonplaceholder.typicode.com/posts')
        response.raise_for_status()
        posts = response.json()

        print("=" * 60)
        print("ПЕРВЫЕ 5 ПОСТОВ С JSONPLACEHOLDER")
        print("=" * 60)

        for i, post in enumerate(posts[:5], 1):
            print(f"\n【ПОСТ {i}】")
            print(f"📌 Заголовок: {post.get('title', '').title()}")
            print(f"📝 Содержание:\n{post.get('body', '')}")
            print("─" * 60)

        # Дополнительная информация
        print(f"\n✅ Всего постов в ответе: {len(posts)}")
        print(f"📊 Выведено постов: 5")

        return posts[:5]

    except Exception as e:
        print(f"❌ Произошла ошибка: {e}")
        return None

# Функция с сохранением в файл
def get_posts_and_save():
    try:
        response = requests.get('https://jsonplaceholder.typicode.com/posts')
        response.raise_for_status()
        posts = response.json()

        first_five = posts[:5]

        # Выводим в консоль
        print("\n" + "="*60)
        print("Первые 5 постов:")
        print("="*60)

        for i, post in enumerate(first_five, 1):
            print(f"\n{i}. {post['title'][:50]}...")
            print(f"   {post['body'][:80]}...")

        # Сохраняем в файл
        with open('first_5_posts.json', 'w', encoding='utf-8') as f:
            json.dump(first_five, f, indent=2, ensure_ascii=False)

        print(f"\n✅ Данные сохранены в файл: first_5_posts.json")
        return first_five

    except Exception as e:
        print(f"❌ Ошибка: {e}")
        return None

if __name__ == "__main__":
    # Используйте любую из этих функций:

    # Простая версия
    # get_posts()

    # Версия с красивым форматированием
    get_posts_formatted()

    # Версия с сохранением в файл
    # get_posts_and_save()