# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10uYJkZ_IZ-ll8LrFbwTVn1aGXm71PkNr
"""

import requests

def get_weather_simple(city):
    """
    Запрос погоды через wttr.in
    """
    try:
        # Формируем URL
        url = f"https://wttr.in/{city}"
        params = {
            'format': 'j1',  # JSON формат
            'lang': 'ru'     # Русский язык
        }

        print(f"🌤 Запрашиваю погоду для: {city}")
        print(f"🔗 URL: {url}")

        response = requests.get(url, params=params, timeout=10)

        if response.status_code == 200:
            data = response.json()

            # Извлекаем данные
            current = data['current_condition'][0]

            print("\n" + "="*40)
            print(f"ПОГОДА В {city.upper()}")
            print("="*40)

            print(f"\n🌡 Температура: {current['temp_C']}°C")
            print(f"🤔 Ощущается как: {current['FeelsLikeC']}°C")
            print(f"☁️ Погода: {current['weatherDesc'][0]['value']}")
            print(f"💧 Влажность: {current['humidity']}%")
            print(f"💨 Ветер: {current['windspeedKmph']} км/ч")
            print(f"🧭 Направление: {current['winddir16Point']}")
            print(f"📊 Давление: {current['pressure']} мбар")
            print(f"👁 Видимость: {current['visibility']} км")

            # Прогноз на сегодня
            print(f"\n📅 Прогноз на сегодня:")
            today = data['weather'][0]
            print(f"   Макс: {today['maxtempC']}°C, Мин: {today['mintempC']}°C")
            print(f"   Восход: {today['astronomy'][0]['sunrise']}")
            print(f"   Закат: {today['astronomy'][0]['sunset']}")

            print("="*40)
            return True

        elif response.status_code == 404:
            print(f"❌ Город '{city}' не найден")
            print("💡 Попробуйте:")
            print("   • Использовать латинские буквы")
            print("   • Уточнить страну: 'London' или 'Москва'")
            return False
        else:
            print(f"❌ Ошибка сервера: {response.status_code}")
            return False

    except requests.exceptions.ConnectionError:
        print("❌ Ошибка подключения к интернету")
        return False
    except requests.exceptions.Timeout:
        print("❌ Таймаут запроса")
        return False
    except Exception as e:
        print(f"❌ Неожиданная ошибка: {e}")
        return False

def main():
    print("="*50)
    print("🌤 БЕСПЛАТНЫЙ ПРОГНОЗ ПОГОДЫ")
    print("="*50)
    print("Использует wttr.in API")
    print("Поддерживает русский язык, не требует API ключа")
    print("="*50)

    # Примеры городов
    print("\n💡 Примеры городов:")
    print("   Moscow, London, Paris, Berlin, Tokyo")
    print("   Нью-Йорк, Пекин, Дубай, Санкт-Петербург")

    while True:
        print("\n" + "-"*50)
        city = input("\nВведите город (или 'выход'): ").strip()

        if city.lower() in ['выход', 'exit', 'quit', 'q', '0']:
            print("\n👋 До свидания!")
            break

        if not city:
            print("⚠️ Введите название города")
            continue

        get_weather_simple(city)

if __name__ == "__main__":
    main()